version: '3'
services:
  app:
    build: .
    ports:
      - "${port}:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:${mongo_port}
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: